// generated by ghost-signal flavor build from flavor.json. do not edit
import { registerExpression, registerIcon, registerSprite } from '../../../src/gs.js';
import { setCopy } from '../../../src/copy.js';

registerExpression('probing', ["................","..##........##..","..##........##..","................","......######....",".........##.....","........##......","................","........##......","................"]);
registerIcon('sigil', ["................",".......##.......","......####......",".....##..##.....","....##....##....","...##..##..##...","..##..####..##..",".##...####...##.",".##...####...##.","..##..####..##..","...##..##..##...","....##....##....",".....##..##.....","......####......",".......##.......","................"]);
registerSprite('probe', ["#.....",".#....","..#...","...#..","....#.",".....#"]);
setCopy('empty', "probe is listening. nothing has pinged yet");
export const app = 'probe';
