import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { check, flavorBuild } from '../../scripts/lib/cli.js';

const run = promisify(execFile);
const fixtures = fileURLToPath(new URL('./fixtures/', import.meta.url));
const bin = fileURLToPath(new URL('../../scripts/ghost-signal.js', import.meta.url));
const f = (name) => join(fixtures, name);

test('a good app manifest and its flavor pass', async () => {
  const r = await check(f('probe-fixture/app.json'));
  assert.deepEqual(r, { ok: true, kind: 'app', errors: [] });
  assert.deepEqual(await check(f('probe-fixture/flavor.json')), { ok: true, kind: 'flavor', errors: [] });
});

test('bad contrast fails on every background it misses, in both themes', async () => {
  const r = await check(f('flavor-bad-contrast.json'));
  assert.equal(r.ok, false);
  assert.equal(r.errors.length, 6);
  assert.match(r.errors[0], /accent2\.dark #3a2a5a on void is \d+\.\d\d:1, needs 4\.5:1/);
  assert.ok(r.errors.some((e) => e.startsWith('accent2.light #c9c0dd on raised')));
});

test('a locked key fails', async () => {
  const r = await check(f('flavor-locked-key.json'));
  assert.equal(r.ok, false);
  assert.deepEqual(r.errors, ['$.accent: not allowed', '$.motion: not allowed']);
});

test('a range that excludes the installed version fails', async () => {
  const r = await check(f('flavor-bad-range.json'));
  assert.deepEqual(r.errors, ['ghostSignal range ^0.2 excludes installed 0.1.0']);
});

test('an app that defines a gs- element fails', async () => {
  const r = await check(f('gs-namespace/app.json'));
  assert.equal(r.ok, false);
  assert.deepEqual(r.errors, ['rogue.js: defines a gs-* custom element; the gs- prefix is reserved']);
});

test('an app with a vendored ghost-signal copy and build output passes', async () => {
  // vendor/ghost-signal holds VERSION + src/gs.js (what sync-ghost-signal.sh writes); dist, build
  // and target hold bundles. every one of them defines gs-* and none of them is the app's code
  assert.deepEqual(await check(f('vendored-app/app.json')), { ok: true, kind: 'app', errors: [] });
});

test('a rogue define in .ts or .mjs fails, and a bare VERSION file does not hide it', async () => {
  const r = await check(f('rogue-ts/app.json'));
  assert.equal(r.ok, false);
  assert.deepEqual(r.errors, [
    'lib/rogue.mjs: defines a gs-* custom element; the gs- prefix is reserved',
    'rogue.ts: defines a gs-* custom element; the gs- prefix is reserved',
  ]);
});

test('flavorBuild emits the data-app css block, a light block and a js registration module', async () => {
  const { css, js, id } = await flavorBuild(f('probe-fixture/flavor.json'), { gsImport: '../../src' });
  assert.equal(id, 'probe');
  assert.match(css, /^\/\* generated by ghost-signal flavor build/);
  assert.match(css, /\[data-app="probe"\] \{\n  --gs-color-accent-2: #b78bff;\n  --gs-font-display: "Iowan Old Style", Palatino, Georgia, serif;\n\}/);
  // compound for data-app on <html> (the consumer layout), descendant for data-app on a subtree
  assert.ok(css.includes(':root[data-theme="light"][data-app="probe"], :root[data-theme="light"] [data-app="probe"] {\n  --gs-color-accent-2: #6b2fc9;\n}'), css);
  assert.doesNotMatch(css, /--gs-dither: none/);
  assert.match(js, /^\/\/ generated by ghost-signal flavor build/);
  assert.match(js, /import \{ registerExpression, registerIcon, registerSprite \} from '\.\.\/\.\.\/src\/gs\.js';/);
  assert.match(js, /import \{ setCopy \} from '\.\.\/\.\.\/src\/copy\.js';/);
  assert.match(js, /registerExpression\('haunting', \["/);
  assert.match(js, /registerIcon\('sigil', \["/);
  assert.match(js, /registerSprite\('probe', \["#\.\.","\.#\.","\.\.#"\]\);/);
  assert.match(js, /setCopy\('empty', "the spirits are quiet"\);/);
  assert.match(js, /export const app = 'probe';/);
  assert.doesNotMatch(css + js, /20\d\d-\d\d-\d\d/);
});

test('flavorBuild refuses a flavor that fails check', async () => {
  await assert.rejects(() => flavorBuild(f('flavor-locked-key.json')), /\$\.accent: not allowed/);
});

test('the bin exits 0, 1 and 2 and writes build output to --out', async () => {
  const ok = await run(process.execPath, [bin, 'check', f('probe-fixture/app.json')]);
  assert.match(ok.stdout, /ok \(app\)/);
  await assert.rejects(run(process.execPath, [bin, 'flavor', 'check', f('flavor-bad-range.json')]), (e) => e.code === 1 && /excludes installed/.test(e.stdout));
  await assert.rejects(run(process.execPath, [bin]), (e) => e.code === 2 && /usage/.test(e.stderr));
  await assert.rejects(run(process.execPath, [bin, 'check', f('missing.json')]), (e) => e.code === 2);
  const out = await mkdtemp(join(fixtures, 'build-'));
  try {
    const built = await run(process.execPath, [bin, 'flavor', 'build', f('probe-fixture/flavor.json'), '--out', out, '--gs-import', 'ghost-signal']);
    assert.match(built.stdout, /wrote .*flavor\.css/);
    assert.match(await readFile(join(out, 'flavor.js'), 'utf8'), /from 'ghost-signal\/gs\.js'/);
    assert.match(await readFile(join(out, 'flavor.css'), 'utf8'), /data-app="probe"/);
  } finally {
    await rm(out, { recursive: true, force: true });
  }
});
